Parameters:

  HudiConnectionName:
    Description: The name of the AWS Glue Connection created in Glue Studio using the deep URL
    Type: String
    Default: a-hudi-connection

  KinesisIteratorPosition:
    Description: The position from where to read from Kinesis stream, valid values are LATEST, TRIM_HORIZON or EARLIEST
    Type: String
    Default: LATEST

  WindowSize:
    Description: The amount of time to spend processing each batch with AWS Glue job
    Type: String
    Default: 10 seconds


Resources:

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "hudi_nta_db"

  KinesisDataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: "hudi_nta_stream"
      ShardCount: 1

  KinesisTableInGlueCatalog:
    Type: AWS::Glue::Table
    DependsOn:
      - GlueDatabase
      - KinesisDataStream
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: "hudi_nta_kinesis_stream_table"
        StorageDescriptor:
          Location: !Ref KinesisDataStream
          Parameters:
            typeOfData: kinesis
            streamARN: !Join ['', ["arn:aws:kinesis:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":stream/", !Ref KinesisDataStream]]
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
        Parameters:
          classification: json

  LocalS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: "hudi-nta-bucket"

  ExecuteGlueHudiJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - "-"
        - - "GlueJobExecutionRoleNTA"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonKinesisReadOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Path: /

  HudiStreamingJob:
    Type: 'AWS::Glue::Job'
    DependsOn:
      - KinesisDataStream
      - GlueDatabase
      - ExecuteGlueHudiJobRole
      - LocalS3Bucket
    Properties:
      Command:
        Name: gluestreaming
        PythonVersion: 3
        ScriptLocation: !Join ['', ["s3://", "a-tech-bucket", "Hudi/artifacts/mainscript.py"]]
      Connections:
        Connections:
          - !Ref HudiConnectionName
      DefaultArguments:
        '--database_name': !Ref GlueDatabase
        '--kinesis_table_name': !Ref KinesisTableInGlueCatalog
        '--hudi_table_name': 'hudi_nta_table'
        '--starting_position_of_kinesis_iterator': !Ref KinesisIteratorPosition
        '--window_size': !Ref WindowSize
        '--s3_path_hudi': !Join ['', ["s3://", !Ref LocalS3Bucket, "/hudi_stuff/hudi_nta_table/"]]
        '--s3_path_spark': !Join ['', ["s3://", !Ref LocalS3Bucket, "/spark_checkpoints/"]]
        '--spark-event-logs-path': !Join ['', ["s3://", !Ref LocalS3Bucket, "/sparkHistoryLogs/"]]
        '--enable-continuous-cloudwatch-log': 'true'
        '--TempDir': !Join ['', ["s3://", !Ref LocalS3Bucket, "/temp"]]
        '--job-language': 'python'
        '--enable-metrics': 'true'
        '--job-bookmark-option': 'job-bookmark-enable'
        '--enable-glue-datacatalog': 'true'
        '--enable-spark-ui': 'true'
        '--class': 'GlueApp'
        "--extra-py-files": "s3://a-tech-bucket/Hudi/Extra/extra.zip"
      ExecutionProperty:
        MaxConcurrentRuns: 2
      GlueVersion: 3.0
      MaxRetries: 0
      Name: "Hudi_Streaming_Job_NTA"
      Role: !GetAtt ExecuteGlueHudiJobRole.Arn
      NumberOfWorkers: 2
      WorkerType: G.1X